### ISSUE TITLE
damaged nifti file in UKBB dataset

### ISSUE THREAD

**Issue by vfonov** [neurohub/neurohub_documentation#12] opened 2021-01-13 18:32 UTC
I came across at least one file so far which seem to be damaged, steps to reproduce:

```
unsquashfs -p 1 -d problematic -f /lustre03/project/6008063/neurohub/ukbb/imaging/neurohub_ukbb_t1w_flat.squashfs neurohub/ukbb/imaging/T1w_niis/sub-1249027_ses-2_T1w.nii.gz
```
then , loading in fsleyes:
```
fsleyes problematic/neurohub/ukbb/imaging/T1w_niis/sub-1249027_ses-2_T1w.nii.gz
```

produces following error:
```
An error occurred loading the image problematic/neurohub/ukbb/imaging/T1w_niis/sub-1249027_ses-2_T1w.nii.gz

Details: Expected 31584000 bytes, got 31583969 bytes from object
 - could the file be damaged?
```
converting from nifti to minc, produces file but with incorrect range

**Comment by dlq** [comment] 2021-01-19 18:09
I can confirm I'm getting
```
➜  ~ gunzip sub-1249027_ses-2_T1w.nii.gz 
gunzip: invalid compressed data--crc error
gunzip: sub-1249027_ses-2_T1w.nii.gz: uncompress failed
➜  ~ gzip -v -t sub-1249027_ses-2_T1w.nii.gz 
gzip: invalid compressed data--crc error
gzip: sub-1249027_ses-2_T1w.nii.gz: uncompress failed
sub-1249027_ses-2_T1w.nii.gz:	  NOT OK
```

**Comment by AlexandreHutton** [comment] 2021-01-20 13:20
You'll need to check with @prioux since he made that dataset. I suspect some kind of error on read/write when the .squashfs was being created. It'll probably need to be squashed again.

**Comment by vfonov** [comment] 2021-01-20 17:03
I encountered this error in 33 other files, here is a full list:
```
sub-1000011
sub-1249027
sub-1290258
sub-1317894
sub-1353426
sub-1384277
sub-1441610
sub-1469495
sub-1826448
sub-2035797
sub-2149805
sub-2244153
sub-2263057
sub-2359972
sub-2393185
sub-2417778
sub-3448181
sub-3598271
sub-4124363
sub-4362028
sub-4440810
sub-4593228
sub-4613949
sub-4644859
sub-4645452
sub-4712015
sub-4744896
sub-4755945
sub-4791922
sub-4832866
sub-5140819
sub-5153661
sub-5744707
sub-5964350
```

in addition to that, sub-2129316_ses-2_T1w.nii.gz seem to be not a gzip file format at all.

**Comment by prioux** [comment] 2021-01-20 17:33
I will recreate the squashfs file; I don't know exactly why some files were corrupted, but it could have happened at many stages during processing.

While I'm at it, I'll include ses-3 files in the list too.

I have checked `sub-1249027_ses-2_T1w.nii.gz` as stored in the other squashfs file (neurohub_ukbb_t1_ses2_0_bids.squashfs) and it `gunzip -c` properly, so at this point I know at least for that one file that I have a non-corrupted source.

**Comment by prioux** [comment] 2021-01-20 17:57
The process is running now. How I'm going about it:

1) Create scratch dir to receive the data
2) connect to a container with the BIDs-formatted T1s for ses-2 and ses-3
3) run mksquashfs from within the container

```
beluga> mkdir /scratch/prioux/r
beluga> singularity shell --overlay neurohub_ukbb_t1_ses2_0_bids.squashfs --overlay neurohub_ukbb_t1_ses3_0_bids.squashfs -B /scratch/prioux/r sing_squashfs.simg                                                           
Singularity> cd /neurohub/ukbb/imaging/                                                                            
Singularity> mksquashfs sub-*/ses*/anat/*.nii.gz /scratch/prioux/r/n.sq -noI -noD -noF -noX -processors 1  
```

I'm at 10% complete now.

Once the squashfs file has been created, I will run one more mksquashfs file in append mode to 're-root' all the files into `/neurohub/ukbb/imaging/T1w_niis/`, like it was.

**Comment by prioux** [comment] 2021-01-20 17:59
I was afraid the argument list for the mksquashfs command would be too long, but at 2.5 million characters the kernel still took it like a champ. Not sure what the limit is in a modern linux?

**Comment by prioux** [comment] 2021-01-20 18:32
The limit can be found with the command `getconf ARG_MAX`. On my CBRAIN main server, a nice powerful linux machine, I have never changed the limit and the default value is this:

```
Ace-cbrain-1 home ~ > getconf ARG_MAX                                                                              
2097152
```

That's 2 million characters.

On beluga however, the sysadmins have changed the default value. They increased it. Slightly. See for yourself:

```
beluga2 ~ > getconf ARG_MAX
4611686018427387903
```

That's.... 4.6 million terabytes.

**Comment by prioux** [comment] 2021-01-20 18:41
That number happens to be (2**62 - 1). Given that modern 64 bit computers don't even have the physical wires to implement all 64 address bus lines, I think I can safely say I'll never exceed that limit.... even if the RAM was installed.

**Comment by prioux** [comment] 2021-01-20 21:25
OK I got a new SquashFS file. The re-rooting was performed with these commands, run in turn:

```
mkdir empty
mksquashfs empty n.sq -root-becomes T1w_niis -noI -noD -noF -noX -processors 1 -no-recovery
mksquashfs empty n.sq -root-becomes imaging -noI -noD -noF -noX -processors 1 -no-recovery
mksquashfs empty n.sq -root-becomes ukbb -noI -noD -noF -noX -processors 1 -no-recovery
mksquashfs empty n.sq -root-becomes neurohub -noI -noD -noF -noX -processors 1 -no-recovery
```

Basically, to re-root under `/neurohub/ukbb/imaging/T1w_niis`, you have to run the mksquashfs commands in reverse order of the path components. So move everything under `/T1w_niis`, then move everythign under `/imaging`, etc.

I will check the list of corrupted files that @vfonov provided, now.

**Comment by prioux** [comment] 2021-01-20 21:34
@AlexandreHutton My new SquashFS file checks out perfectly. How do I move it in place of the old one, given I don't have write access to this directory? I could just copy it over the existing file.... but that would mean several minutes where the dataset is 'bad'.

I'd like:
1) to copy the file under a temp name in the dir
2) once the copy is over, quickly rename it, so that it replaces the old file atomically (processes still using the old file will be fine even if it disappear)

**Comment by AlexandreHutton** [comment] 2021-01-20 21:58
Just to update since there was some back-and-forth elsewhere: the new .squashfs is being transferred to Beluga and will replace the old .squashfs tomorrow.

**Comment by prioux** [comment] 2021-01-21 17:29
It's been ready since 5:17 PM yesterday but I only notified Alex this morning. Sorry about that,

**Comment by vfonov** [comment] 2021-01-21 17:35
```
ls -lt /lustre03/project/6008063/neurohub/ukbb/imaging/neurohub_ukbb_t1w_flat.squashfs
-r-xr-x---+ 1 prioux rpp-aevans-ab 448182292480 Jul 13  2020 /lustre03/project/6008063/neurohub/ukbb/imaging/neurohub_ukbb_t1w_flat.squashfs

```

**Comment by prioux** [comment] 2021-01-21 18:02
What I'm saying @vfonov is that the file is ready, in a staging area, but Alex needs to install it to replace the faulty one. I don't have the permissions.

**Comment by prioux** [comment] 2021-01-21 18:04
By the way, you'll also get the T1 for `ses-3` in there. I figured I might as well include them.

**Comment by AlexandreHutton** [comment] 2021-01-21 19:15
The file has been swapped and the issue can be closed.

**Closed as completed** 2021-01-21 19:16 UTC

**Comment by prioux** [comment] 2021-01-21 19:19
Er, I was going to close this, but dlq did it first.

**Comment by vfonov** [comment] 2021-01-21 21:15
Now I don't have permission to read this file
```
$ unsquashfs -l /lustre03/project/6008063/neurohub/ukbb/imaging/neurohub_ukbb_t1w_flat.squashfs
Could not open /lustre03/project/6008063/neurohub/ukbb/imaging/neurohub_ukbb_t1w_flat.squashfs, because Permission denied
```

**Comment by AlexandreHutton** [comment] 2021-01-26 15:50
Update just for future tracking: permissions were updated.
